# Generated by Django 5.1.4 on 2024-12-28 08:23

import ecommerce.models
import enumchoicefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(help_text="Mapping of Product id and it's quantities")),
                ('status', enumchoicefield.fields.EnumChoiceField(default=ecommerce.models.OrderState['PENDING'], enum_class=ecommerce.models.OrderState, help_text='Shows the current state of Order', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Product')),
                ('description', models.TextField(blank=True, help_text='Description of the Product', null=True)),
                ('price', models.FloatField(help_text='Price of the Product')),
                ('stock', models.PositiveIntegerField(help_text='Available Quantities of the Product')),
            ],
        ),
    ]
